// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjydiorocaixosezpylh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqeWRpb3JvY2FpeG9zZXpweWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4Njk1MzYsImV4cCI6MjA1MjQ0NTUzNn0.6tXBsBOaki8CByfj_km-1_Jwv9xoRsi3CCcGiMFa568";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);